[features]
seeds = false
skip-lint = false

[programs.localnet]
graph_arbitrage = "E3evReispCGYdx9XLp27u2BNBBrBEX8XfDjUhrNK9wwm"

[programs.devnet]
graph_arbitrage = "E3evReispCGYdx9XLp27u2BNBBrBEX8XfDjUhrNK9wwm"

[programs.mainnet]
graph_arbitrage = "E3evReispCGYdx9XLp27u2BNBBrBEX8XfDjUhrNK9wwm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/albertalov/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"